services:
  web:
    image: jitsi/web:stable
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${CONFIG}/web:/config
      - ${CONFIG}/web/letsencrypt:/etc/letsencrypt
    depends_on:
      - prosody
      - jicofo
      - jvb
    networks:
      - meet.jitsi
      - dokploy-network

  prosody:
    image: jitsi/prosody:stable
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${CONFIG}/prosody:/config
      - ${CONFIG}/prosody/prosody-plugins-custom:/prosody-plugins-custom
    networks:
      meet.jitsi:
        aliases:
          - xmpp.meet.jitsi

  jicofo:
    image: jitsi/jicofo:stable
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${CONFIG}/jicofo:/config
    depends_on:
      - prosody
    networks:
      meet.jitsi:

  jvb:
    image: jitsi/jvb:stable
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${CONFIG}/jvb:/config
    ports:
      - "${JVB_PORT}:10000/udp"
      - "${JVB_TCP_PORT}:4443/tcp"
    depends_on:
      - prosody
    networks:
      meet.jitsi:

volumes: {}

networks:
  meet.jitsi:
  dokploy-network:
    external: true