services:
  web:
    image: jitsi/web:stable
    restart: unless-stopped

    env_file:
      - .env

    depends_on:
      - prosody
      - jicofo
      - jvb

    networks:
      meet.jitsi:
        aliases:
          - xmpp.meet.jitsi
          - auth.meet.jitsi

      dokploy-network: {}

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jitsi.rule=Host(`eway-meet.studentplus2.in`)"
      - "traefik.http.routers.jitsi.entrypoints=websecure"
      - "traefik.http.routers.jitsi.tls.certresolver=letsencrypt"
      - "traefik.http.services.jitsi.loadbalancer.server.port=80"

    volumes:
      - ${CONFIG}/web:/config
      - ${CONFIG}/web/letsencrypt:/etc/letsencrypt
      - ${CONFIG}/web/title.html:/usr/share/jitsi-meet/title.html
      - ${CONFIG}/web/config.js:/usr/share/jitsi-meet/config.js
      - ${CONFIG}/web/lang/main.json:/usr/share/jitsi-meet/lang/main.json
      - ${CONFIG}/web/lang/main-en.json:/usr/share/jitsi-meet/lang/main-en.json
      - ${CONFIG}/web/lang/main-en-US.json:/usr/share/jitsi-meet/lang/main-en-US.json
      - ${CONFIG}/web/interface_config_custom_v2.js:/usr/share/jitsi-meet/interface_config.js
      - ${CONFIG}/web/images/watermark.svg:/usr/share/jitsi-meet/images/watermark.svg
      - ${CONFIG}/web/images/logo.png:/usr/share/jitsi-meet/images/logo.png

  prosody:
    image: jitsi/prosody:stable
    restart: unless-stopped

    env_file:
      - .env

    networks:
      meet.jitsi:
        aliases:
          - xmpp.meet.jitsi
          - auth.meet.jitsi
          - muc.meet.jitsi
          - internal-muc.meet.jitsi

    volumes:
      - ${CONFIG}/prosody:/config
      - ${CONFIG}/prosody/prosody-plugins-custom:/prosody-plugins-custom

  jicofo:
    image: jitsi/jicofo:stable
    restart: unless-stopped

    env_file:
      - .env

    depends_on:
      - prosody

    networks:
      meet.jitsi:
        aliases:
          - jicofo.meet.jitsi

    volumes:
      - ${CONFIG}/jicofo:/config

  jvb:
    image: jitsi/jvb:stable
    restart: unless-stopped

    env_file:
      - .env

    depends_on:
      - prosody

    ports:
      - "10000:10000/udp"
      - "4443:4443/tcp"

    networks:
      meet.jitsi:
        aliases:
          - jvb.meet.jitsi

    volumes:
      - ${CONFIG}/jvb:/config

volumes: {}

networks:
  meet.jitsi:
    driver: bridge

  dokploy-network:
    external: true